In [3]:
import numpy as np
x1=np.array([1,2,5,66])
x2=np.array([[11,22,3],[4,5,44]])
print("x1:",x1)
print("x2:",x2)

x1: [ 1  2  5 66]
x2: [[11 22  3]
 [ 4  5 44]]


In [4]:
x1

array([ 1,  2,  5, 66])

In [5]:
x1[0]  ##Acess the 1st element from x1 array

1

In [6]:
x1[-1]  ##Acess the last element from x1 array

66

In [7]:
x1[0:]

array([ 1,  2,  5, 66])

In [8]:
x1[0: :3]

array([ 1, 66])

In [10]:
x2

array([[11, 22,  3],
       [ 4,  5, 44]])

In [11]:
x2[0]

array([11, 22,  3])

In [12]:
x2[:]

array([[11, 22,  3],
       [ 4,  5, 44]])

In [13]:
x2[:,0]

array([11,  4])

In [14]:
x2[0][0]

11

In [15]:
for i in x2:
    print(i)

[11 22  3]
[ 4  5 44]


In [16]:
x3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
x3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [17]:
x3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
x3[0][0]

array([1, 2, 3])

In [19]:
x3[0:,0:,]

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [20]:
x3[0:,0:,0]

array([[1, 4, 7]])

In [22]:
x3[0:,0:,0]



array([[1, 4, 7]])

In [23]:
x3[0:,0:2]

array([[[1, 2, 3],
        [4, 5, 6]]])

In [27]:
x3[0:,0:,0:2]

array([[[1, 2],
        [4, 5],
        [7, 8]]])

In [28]:
x3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

### Filtering
- To get important features we need to filter the data

In [30]:
a=np.arange(1,50)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [31]:
a%2==0

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False])

In [33]:
a[a%2==0]   ##functional mapping

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48])

In [34]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [36]:
a>=25

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [37]:
a[(a>=25)&(a>=40)&(a%2==0)]

array([40, 42, 44, 46, 48])

### Statistics

In [38]:
x1

array([ 1,  2,  5, 66])

In [39]:
np.max(x1)

66

In [40]:
np.mean(x1)

18.5

In [42]:
np.median(x1)

3.5

In [45]:
np.sum(x1)

74

In [46]:
np.std(x1)

27.463612289718917

In [47]:
np.percentile(x1,25)

1.75

### Aggrigation Functions

In [48]:
x2

array([[11, 22,  3],
       [ 4,  5, 44]])

In [49]:
x2.sum()

89

In [50]:
x2.min()

3

In [51]:
x2.max()

44

In [52]:
x2.argmax()

5

In [53]:
x2.cumsum()

array([11, 33, 36, 40, 45, 89], dtype=int32)

In [54]:
x2.argmin(axis=0)

array([1, 1, 0], dtype=int64)

In [55]:
x2.cumsum()

array([11, 33, 36, 40, 45, 89], dtype=int32)

### Saving Data

In [57]:
x=np.random.rand(1,10)
x

array([[0.59923962, 0.89201701, 0.2306204 , 0.39769661, 0.6430512 ,
        0.28008283, 0.12557544, 0.53224514, 0.40694356, 0.14384596]])

In [58]:
np.save("x.npy",x)

In [59]:
np.load("x.npy")

array([[0.59923962, 0.89201701, 0.2306204 , 0.39769661, 0.6430512 ,
        0.28008283, 0.12557544, 0.53224514, 0.40694356, 0.14384596]])

### Numpy copy and view
- copy
   - changes will not effected to the original array  ..visversa
- view
   - changes will effected to the original array if change copied array
       -visversa

In [60]:
import numpy as np
arr=np.array([1,2,3,4])
x=arr.copy()
print("copied array",x)
print("main array",arr)

copied array [1 2 3 4]
main array [1 2 3 4]


In [61]:
import numpy as np
arr=np.array([1,2,3,4])
x=arr.copy()
arr[0]=40
print("copied array",x)
print("main array",arr)

copied array [1 2 3 4]
main array [40  2  3  4]


### Numpy joining Arrays
- np.concatenate()

In [65]:
import numpy as np
a1=np.array([1,2,3])
a2=np.array([5,6,7])
a3=np.concatenate((a1,a2))
a3

array([1, 2, 3, 5, 6, 7])

In [66]:
import numpy as np
b1=np.array([[1,2,3],[4,5,6]])
b2=np.array([[5,6,7],[8,9,10]])
b3=np.concatenate((b1,b2))
b3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [67]:
np.hstack((b1,b2))

array([[ 1,  2,  3,  5,  6,  7],
       [ 4,  5,  6,  8,  9, 10]])

In [68]:
np.vstack((a1,a2))

array([[1, 2, 3],
       [5, 6, 7]])

### Numpy Math Functions
- sin
- cos
- tan

In [69]:
np.matrix('1 2;3 4')

matrix([[1, 2],
        [3, 4]])

In [72]:
x.transpose()

array([1, 2, 3, 4])

In [73]:
x.sort()

In [74]:
x

array([1, 2, 3, 4])

In [75]:
a1=np.arange(1,100)
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [77]:
np.sin(a1)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111,
       -0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784,
       -0.28790332, -0.96139749, -0.75098725,  0.14987721,  0.91294525,
        0.83665564, -0.00885131, -0.8462204 , -0.90557836, -0.13235175,
        0.76255845,  0.95637593,  0.27090579, -0.66363388, -0.98803162,
       -0.40403765,  0.55142668,  0.99991186,  0.52908269, -0.42818267,
       -0.99177885, -0.64353813,  0.29636858,  0.96379539,  0.74511316,
       -0.15862267, -0.91652155, -0.83177474,  0.01770193,  0.85090352,
        0.90178835,  0.12357312, -0.76825466, -0.95375265, -0.26237485,
        0.67022918,  0.98662759,  0.39592515, -0.55878905, -0.99975517,
       -0.521551  ,  0.43616476,  0.99287265,  0.63673801, -0.30481062,
       -0.96611777, -0.7391807 ,  0.1673557 ,  0.92002604,  0.82682868,
       -0.02655115, -0.85551998, -0.89792768, -0.11478481,  0.77

In [78]:
np.exp(a1)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
       3.93133430e+12, 1.06864746e+13, 2.90488497e+13, 7.89629602e+13,
       2.14643580e+14, 5.83461743e+14, 1.58601345e+15, 4.31123155e+15,
       1.17191424e+16, 3.18559318e+16, 8.65934004e+16, 2.35385267e+17,
       6.39843494e+17, 1.73927494e+18, 4.72783947e+18, 1.28516001e+19,
       3.49342711e+19, 9.49611942e+19, 2.58131289e+20, 7.01673591e+20,
       1.90734657e+21, 5.18470553e+21, 1.40934908e+22, 3.83100800e+22,
       1.04137594e+23, 2.83075330e+23, 7.69478527e+23, 2.09165950e+24,
      

In [79]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738,
       3.4339872 , 3.4657359 , 3.49650756, 3.52636052, 3.55534806,
       3.58351894, 3.61091791, 3.63758616, 3.66356165, 3.68887945,
       3.71357207, 3.73766962, 3.76120012, 3.78418963, 3.80666249,
       3.8286414 , 3.8501476 , 3.87120101, 3.8918203 , 3.91202301,
       3.93182563, 3.95124372, 3.97029191, 3.98898405, 4.00733319,
       4.02535169, 4.04305127, 4.06044301, 4.07753744, 4.09434456,
       4.11087386, 4.12713439, 4.14313473, 4.15888308, 4.17438727,
       4.18965474, 4.20469262, 4.21950771, 4.2341065 , 4.24849524,
       4.26267988, 4.27666612, 4.29045944, 4.30406509, 4.31748