### Data Analysis Libraries
- Numpy
- Pandas
- Matplotlib
- Seaborn
- scipy

### Numpy
- we can create arrays using numpy ex:zero dimensional,single,two,multi dimensional arrays
- Numerical Python

In [1]:
import numpy

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [5]:
np.__version__

'1.20.1'

### Creating arrays

In [6]:
import numpy as np
x=np.array(23)
print(x)

23


In [7]:
## check dimension
np.ndim(x)

0

In [8]:
x1=np.array([12,23,4,5,6])
print(x1)
print(np.ndim(x1))

[12 23  4  5  6]
1


In [9]:
## 2D array
x2=np.array([[1,2,3],[4,5,6]])
print(x2)
print("Dimension of x2",np.ndim(x2))

[[1 2 3]
 [4 5 6]]
Dimension of x2 2


In [10]:
## no of elements
np.size(x2)

6

In [11]:
## To get no of rows and columns
np.shape(x2)

(2, 3)

### 3D Array


In [13]:
import numpy as np
x3=np.array([[[1,2,3],[6,7,8],[4,7,9]]])
print(x3)
print("dimension of x3",np.ndim(x3))
print("elements of x3:",np.size(x3))
print("shape of x3:",np.shape(x3))

[[[1 2 3]
  [6 7 8]
  [4 7 9]]]
dimension of x3 3
elements of x3: 9
shape of x3: (1, 3, 3)


## Methods to create arrays
- Zeros
- Ones
- linspace
- logspace
- arrange

In [14]:
a0=np.zeros(4,dtype=int)
print(a0)

[0 0 0 0]


In [18]:
a0=np.zeros(4,dtype=str)
print(a0)

['' '' '' '']


In [16]:
a0=np.ones(4,dtype=int)
print(a0)

[1 1 1 1]


In [17]:
a0=np.ones(4,dtype=str)
print(a0)

['1' '1' '1' '1']


In [20]:
a0=np.ones(4)  ## float by default
print(a0)

[1. 1. 1. 1.]


In [24]:
a0=np.ones(5,dtype=int)
a1=a0.reshape(1,5)
print(a1)
a2=a1.reshape(1,5)
print(a2)

[[1 1 1 1 1]]
[[1 1 1 1 1]]


In [25]:
a0=np.ones(5,dtype=int)
a1=a0.reshape(5,1)
print(a1)
a2=a1.reshape(1,5)
print(a2)

[[1]
 [1]
 [1]
 [1]
 [1]]
[[1 1 1 1 1]]


In [29]:
import numpy as np
a=np.arange(1,12,2)
print(a)
print(np.ndim(a))
print(np.size(a))

[ 1  3  5  7  9 11]
1
6


### Posibilities to reshape of 6 elements
- (2,3)
- (3,2)
- (6,1)
- (1,6)

In [31]:
a1=a.reshape(3,2)
print(a)
print(a1)

[ 1  3  5  7  9 11]
[[ 1  3]
 [ 5  7]
 [ 9 11]]


In [33]:
l1=np.logspace(1,5)
print(l1)

[1.00000000e+01 1.20679264e+01 1.45634848e+01 1.75751062e+01
 2.12095089e+01 2.55954792e+01 3.08884360e+01 3.72759372e+01
 4.49843267e+01 5.42867544e+01 6.55128557e+01 7.90604321e+01
 9.54095476e+01 1.15139540e+02 1.38949549e+02 1.67683294e+02
 2.02358965e+02 2.44205309e+02 2.94705170e+02 3.55648031e+02
 4.29193426e+02 5.17947468e+02 6.25055193e+02 7.54312006e+02
 9.10298178e+02 1.09854114e+03 1.32571137e+03 1.59985872e+03
 1.93069773e+03 2.32995181e+03 2.81176870e+03 3.39322177e+03
 4.09491506e+03 4.94171336e+03 5.96362332e+03 7.19685673e+03
 8.68511374e+03 1.04811313e+04 1.26485522e+04 1.52641797e+04
 1.84206997e+04 2.22299648e+04 2.68269580e+04 3.23745754e+04
 3.90693994e+04 4.71486636e+04 5.68986603e+04 6.86648845e+04
 8.28642773e+04 1.00000000e+05]


In [34]:
l1=np.logspace(1,5,3)
print(l1)

[1.e+01 1.e+03 1.e+05]


In [36]:
l2=np.linspace(1,5)
l2

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [37]:
l2=np.linspace(1,5,5)
l2

array([1., 2., 3., 4., 5.])

In [38]:
r=np.random.rand(3,2)
r

array([[0.35638789, 0.24771875],
       [0.29605931, 0.47885383],
       [0.47070363, 0.50893166]])

In [40]:
r1=np.random.randint(1,10)   ## random integer
r1

9

In [41]:
r1=np.random.randint(1,100)   ## random integer
r1

99

In [43]:
r1=np.random.randn(1,10)  
r1

array([[-2.52373869,  0.35581505, -0.00698427,  0.12824909,  0.55881859,
        -0.59740599, -1.63432343,  0.2555712 , -0.0313912 , -1.27574614]])

In [44]:
np.ndim(r1)

2

In [46]:
r2=r1.flatten()
r2

array([-2.52373869,  0.35581505, -0.00698427,  0.12824909,  0.55881859,
       -0.59740599, -1.63432343,  0.2555712 , -0.0313912 , -1.27574614])

In [48]:
np.ndim(r2)

1

### Accessing Elements in Arrays
1. indexing
    - -ve
    - +ve
2.Slicing
    -[start:stop:step]
3.Loop
    - for
    - while